- name: "Télécharger l'image scp depuis Docker Hub"
  community.docker.docker_image:
    name: "{{ docker_scp_repo }}"
    tag: 'latest'
    source: pull

# - name: Démarrer le conteneur scp avec auto-restart
#   community.docker.docker_container:
#     name: "scp"
#     image: "{{ docker_scp_repo }}:latest"
#     state: started
#     restart_policy: always
#     ports:
#       - "2222:22"