- name: Télécharger l'image Nginx depuis Docker Hub
  community.docker.docker_image:
    name: nginx
    tag: latest
    source: pull

- name: Démarrer le conteneur Nginx avec auto-restart
  community.docker.docker_container:
    name: my_nginx
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"