- name: Deploiement de la configuration d'un site
  block:
    - name: Création du dossier pour nginx
      ansible.builtin.file:
        dest: '/var/lib/nginx/conf.d'
        state: directory
        owner: 'root'
        group: 'root'
        mode: 0755
        recurse: yes

    - name: Déploiement de la configuration pour nginx
      ansible.builtin.template:
        src: 'nginx.conf.j2'
        dest: '/var/lib/nginx/nginx.conf'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: Déploiement du gabarit application.conf
      ansible.builtin.template:
        src: 'application.conf.j2'
        dest: '/var/lib/nginx/conf.d/application.conf'
        owner: 'root'
        group: 'root'
        mode: 0644

  when:
    - docker_nginx_server_name | default('') | length > 0
    - docker_nginx_backend_servers | length > 0 


- name: Télécharger l'image Nginx depuis Docker Hub
  community.docker.docker_image:
    name: nginx
    tag: "{{ docker_nginx_version }}"
    source: pull

- name: Démarrer le conteneur Nginx avec auto-restart
  community.docker.docker_container:
    name: nginx
    image: "nginx:{{ docker_nginx_version }}"
    state: started
    restart_policy: always
    recreate: true
    ports:
      - "80:80"
    volumes: "{{ docker_nginx_volumes }}"