- name: 'Installation du logiciel PostgreSQL'
  ansible.builtin.apt:
    name: 'postgresql-client'
    state: present
    update_cache: yes

- name: Télécharger l'image PostgreSQL depuis Docker Hub
  community.docker.docker_image:
    name: postgres
    tag: "{{ docker_postgresql_version }}"
    source: pull

# - name: Démarrer le conteneur PostgreSQL avec auto-restart
#   community.docker.docker_container:
#     name: postgresql
#     image: "postgres:{{ docker_postgresql_version }}"
#     state: started
#     restart_policy: always
#     env:
#       POSTGRES_PASSWORD: "{{ docker_postgresql_password }}"
#     ports:
#       - "5432:5432"

# - name: 'Attendre que PostgreSQL soit prêt'
#   wait_for:
#     host: "127.0.0.1"
#     port: 5432
#     delay: 5
#     timeout: 60
#     state: started