- name: 'Installation du logiciel PostgreSQL'
  ansible.builtin.apt:
    name: 'postgresql-client'
    state: present
    update_cache: yes

- name: "Télécharger l'image PostgreSQL depuis Docker Hub"
  community.docker.docker_image:
    name: postgres
    tag: "{{ docker_postgresql_version }}"
    source: pull
