- name: "Télécharger l'image iperf3 depuis Docker Hub"
  community.docker.docker_image:
    name: "{{ docker_iperf3_repo }}"
    tag: 'latest'
    source: pull

- name: 'Démarrer le conteneur iperf3 avec auto-restart'
  community.docker.docker_container:
    name: "iperf3"
    image: "{{ docker_iperf3_repo }}:latest"
    state: started
    restart_policy: always
    ports:
        - "5201:5201/tcp"
        - "5201:5201/udp"