---

- name: "Mise à jour de l'OS"
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
  register: apt_update

- name: 'Redémarrer la VM'
  ansible.builtin.reboot:
  when: apt_update.changed

- name: 'Installation des applications communes'
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ commun_applications }}"

- name: 'Ajout des IP dans /etc/hosts'
  ansible.builtin.template:
     src: 'hosts.j2'
     dest: '/etc/hosts'
     owner: 'root'
     group: 'root'
     mode: 0644