---
- name: Installation environnement SCP_Docker
  hosts: SCP_Docker
  become: true

  tasks:
    - name: Appel du role commun
      ansible.builtin.include_role:
        name: commun
      vars:
        commun_applications: "{{ applications }}"
        commun_hosts: "{{ hosts }}"


# ssh-key -- traité si docker et mettre la clé ailleur pour faire le mount
# Refaire l'image docker sans la clé
# Faire attention de mettre le docker sur un autre port à cause du 22 déjà pris