---
- name: Installation environnement bastion
  hosts: bastion
  become: true

  tasks:
    - name: Appel du role commun
      ansible.builtin.include_role:
        name: commun
      vars:
        commun_applications: "{{ applications }}"
        commun_hosts: "{{ hosts }}"

    - name: Appel du role bastion
      ansible.builtin.include_role:
        name: bastion
      vars:
        bastion_applications: "{{ additionals_applications }}"

    - name: Appel du role git-clone
      ansible.builtin.include_role:
        name: git-clone
      vars:
        git_clone_url: "{{ git_url }}"
        git_clone_local_path: "{{ git_local_path }}"
