---
- name: Installation environnement Demarrage_Docker
  hosts: Demarrage_Docker
  become: true

  tasks:
    - name: Appel du role commun
      ansible.builtin.include_role:
        name: commun
      vars:
        commun_applications: "{{ applications }}"
        commun_hosts: "{{ hosts }}"

    - name: Appel du role docker-ce
      ansible.builtin.include_role:
        name: docker-ce
      vars:
        docker_ce_version: "{{ docker_version }}"

    - name: Appel du role docker-nginx
      ansible.builtin.include_role:
        name: docker-nginx
      vars:
        docker_nginx_version: "{{ nginx_version }}"
        docker_nginx_server_name: "{{ nginx_server_name | default('') }}"
        docker_nginx_backend_servers: "{{ nginx_backend_servers | default([]) }}"
        docker_nginx_volumes: "{{ nginx_volumes | default([]) }}"