---
- name: Installation environnement dev
  hosts: dev-server
  become: true

  tasks:
    - name: Appel du role commun
      ansible.builtin.include_role:
        name: commun
      vars:
        commun_applications: "{{ applications }}"
        commun_hosts: "{{ hosts }}"

    - name: Appel du role bastion
      ansible.builtin.include_role:
        name: bastion
      vars:
        bastion_applications: "{{ additionals_applications }}"

    - name: Appel du role docker-ce
      ansible.builtin.include_role:
        name: docker-ce
      vars:
        docker_ce_version: "{{ docker_version }}"

    - name: Appel du role docker-nginx
      ansible.builtin.include_role:
        name: docker-nginx
      vars:
        docker_nginx_version: "{{ nginx_version }}"

    - name: Appel du role git-clone
      ansible.builtin.include_role:
        name: git-clone
      vars:
        git_clone_url: "{{ git_url }}"
        git_clone_local_path: "{{ git_local_path }}"

    - name: Appel du role docker-iperf3
      ansible.builtin.include_role:
        name: docker-iperf3
      vars:
        docker_iperf3_repo: "{{ iperf3_repo }}"

    - name: Appel du role docker-scp
      ansible.builtin.include_role:
        name: docker-scp
      vars:
        docker_scp_repo: "{{ scp_repo }}"

    - name: Appel du role docker-sysbench
      ansible.builtin.include_role:
        name: docker-sysbench
      vars:
        docker_sysbench_repo: "{{ sysbench_repo }}"
