---
- name: Installation environnement Memoire_Docker
  hosts: Memoire_Docker
  become: true

  tasks:
    - name: 'Appel du role commun'
      ansible.builtin.include_role:
        name: commun
      vars:
        commun_applications: "{{ applications }}"
        commun_hosts: "{{ hosts }}"

    - name: 'Appel du role docker-ce'
      ansible.builtin.include_role:
        name: docker-ce
      vars:
        docker_ce_version: "{{ docker_version }}"

    - name: 'Appel du role docker-sysbench'
      ansible.builtin.include_role:
        name: docker-sysbench
      vars: 
        docker_sysbench_repo: "{{ sysbench_repo }}"