---
- name: Installation environnement Memoire_Docker
  hosts: Memoire_Docker
  become: true

  tasks:
    - name: Appel du role commun
      ansible.builtin.include_role:
        name: commun
      vars:
        commun_applications: "{{ applications }}"
        commun_hosts: "{{ hosts }}"