---
- name: Installation environnement Applicatif_Docker
  hosts: Applicatif_Docker
  become: true

  tasks:
    - name: 'Appel du role commun'
      ansible.builtin.include_role:
        name: 'commun'
      vars:
        commun_applications: "{{ applications }}"
        commun_hosts: "{{ hosts }}"

    - name: 'Appel du role docker-ce'
      ansible.builtin.include_role:
        name: 'docker-ce'
      vars:
        docker_ce_version: "{{ docker_version }}"

    - name: Appel du role docker-postgresql
      ansible.builtin.include_role:
        name: docker-postgresql
      vars:
        docker_postgresql_password: "{{ postgres_password }}"
