---
- name: Installation environnement Applicatif_VM
  hosts: Applicatif_VM
  become: true

  tasks:
    - name: 'Appel du role commun'
      ansible.builtin.include_role:
        name: commun
      vars:
        commun_applications: "{{ applications }}"
        commun_hosts: "{{ hosts }}"

    - name: 'Appel du role postgresql'
      ansible.builtin.include_role:
        name: postgresql
      vars:
        postgresql_user: "{{ postgres_user }}"
        postgresql_password: "{{ postgres_password }}"