---
- name: Installation environnement Processeur_VM
  hosts: Processeur_VM
  become: true

  tasks:
    - name: 'Appel du role commun'
      ansible.builtin.include_role:
        name: commun
      vars:
        commun_applications: "{{ applications }}"
        commun_hosts: "{{ hosts }}"

    - name: 'Appel du role sysbench'
      ansible.builtin.include_role:
        name: sysbench