---

- name: Installation environnement bastion
  hosts: bastion
  become: true
  vars:
      ansible_ssh_common_args: ''
      
  tasks:
    - name: Appel du role file-generator
      ansible.builtin.include_role:
        name: file-generator
      vars:
        file_generator_size_gb: "{{ scp_file_size | default(1) }}"
        file_generator_path: "{{ scp_file_path }}"
  

- name: Installation environnement SCP_Docker
  hosts: SCP_Docker
  become: true

  tasks:
    - name: Appel du role commun
      ansible.builtin.include_role:
        name: commun
      vars:
        commun_applications: "{{ applications }}"
        commun_hosts: "{{ hosts }}"

    - name: Appel du role docker-scp
      ansible.builtin.include_role:
        name: docker-scp
      vars:
        docker_scp_repo: "{{ scp_repo }}"