additionals_applications:
  - 'postgresql-client'
  - 'apache2-utils'
  - 'iperf3'
  - 'sysbench'
  - 'python3-pip'
  - 'python3-fastapi'
  - 'uvicorn'
  - 'net-tools'

# nginx_server_name: 'demo.inf1430'
# nginx_backend_servers: 
#   - '192.168.160.4:8000'
# nginx_volumes:
#   - '/var/lib/nginx/conf.d:/etc/nginx/conf.d'
#   - '/var/lib/nginx/nginx.conf:/etc/nginx/nginx.conf'


