additionals_applications:
  - 'postgresql-client'
  - 'apache2-utils'
  - 'iperf3'
  - 'sysbench'
  - 'python3-pip'
  - 'python3-fastapi'
  - 'uvicorn'
  - 'net-tools'

# nginx_server_name: 'demo.inf1430'
# nginx_backend_servers: 
#   - '192.168.160.4:8000'
# nginx_volumes:
#   - '/var/lib/nginx/conf.d:/etc/nginx/conf.d'
#   - '/var/lib/nginx/nginx.conf:/etc/nginx/nginx.conf'

postgresql_user: 'administrateur'
postgresql_password: 'Bonjour123!'
postgresql_db: 'inf1430-dev'
postgresql_volumes:
  - '/var/lib/postgresql/data:/var/lib/postgresql/data'

iperf3_repo: 'jseb00/iperf3'