FROM alpine:3.21.3

RUN apk add --no-cache \
    openssh \
    bash \
    && rm -rf /var/cache/apk/*

RUN mkdir -p /root/.ssh && \
    mkdir -p /var/run/sshd

COPY ./ssh_keys/authorized_keys /root/.ssh/authorized_keys

RUN chmod 600 /root/.ssh/authorized_keys

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]